# Generated by Django 2.2 on 2019-01-17 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestOne', models.CharField(max_length=255)),
                ('guestTwo', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('YES', 'Yes, I am delighted to attend'), ('NO', 'No, I am sorry, we will have to celebrate another time')], default=None, max_length=3, null=True)),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('eventName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RSVPUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
