# Generated by Django 2.2 on 2019-01-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190111_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.Event'),
        ),
    ]
