# Generated by Django 2.2 on 2019-01-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190111_0609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
