# Generated by Django 2.2 on 2019-01-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_sitepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepage',
            name='pagetitle',
        ),
    ]
